#!/bin/bash
# NEXUS TRADING AI - VIDEO DEMO STARTUP GUIDE
# Ready April 12, 2026

echo "🚀 NEXUS Trading AI - Video Demo Ready!"
echo "=========================================="
echo ""
echo "✅ All 4 agents thinking continuously"
echo "✅ Live parameters enforced"
echo "✅ Dashboard with refresh controls"
echo "✅ On-chain RiskRouter ready"
echo ""

echo "📋 DEMO STARTUP STEPS:"
echo ""
echo "1️⃣  Terminal 1 - Start Trading Engine (shows agent thinking)"
echo "   cd /Users/thapelodipela/Desktop/nexus-trading-ai"
echo "   python main.py --live --verbose"
echo ""

echo "2️⃣  Terminal 2 - Start Dashboard Server (shows live metrics)"
echo "   cd /Users/thapelodipela/Desktop/nexus-trading-ai"
echo "   python dashboard_server.py"
echo ""

echo "3️⃣  Browser - Open Dashboard (shows interactive UI)"
echo "   open http://localhost:5000"
echo ""

echo "4️⃣  Demo Recording (capture both terminal and browser)"
echo "   - Show agents thinking in Terminal 1 (watch for 2-3 cycles)"
echo "   - Demonstrate refresh button in browser"
echo "   - Point out Risk Guardian veto in logs"
echo "   - Show consensus agreement on agent votes"
echo ""

echo "📊 EXPECTED OBSERVATIONS:"
echo ""
echo "Agent Analysis Output (every 5 minutes):"
echo "  • momentum: RSI=65, MACD=0.02, BB score=0.82"
echo "  • sentiment: Fear/Greed=16, trending=-10, community=+44"
echo "  • risk_guardian: Position=20% (VETO)"
echo "  • mean_reversion: RSI < 30 check"
echo ""

echo "Consensus Decision:"
echo "  • BUY score = Σ(agent_weight × confidence)"
echo "  • SELL score = Σ(agent_weight × confidence)"
echo "  • Final direction: HOLD (insufficient confidence)"
echo ""

echo "Dashboard Metrics:"
echo "  • Current price from PRISM/Kraken"
echo "  • 24h volume and price change"
echo "  • Agent weights and recent PnL"
echo "  • Equity curve showing trades"
echo "  • Risk metrics (drawdown, volatility)"
echo ""

echo "🔐 ON-CHAIN VERIFICATION:"
echo "  • RiskRouter connected: 0xd6A6952545FF6E6E6681c2d15C59f9EB8F40FdBC"
echo "  • Agent wallet: 0xF987B94427bDe78bb67Ef91C722015AC69de55C5"
echo "  • Chain: Ethereum Sepolia (11155111)"
echo "  • Trade signature and submission logged"
echo ""

echo "⚙️  CONFIGURATION (Live - Not Cached):"
echo "  • MAX_LEVERAGE: 3.0x"
echo "  • MAX_POSITION_PCT: 20%"
echo "  • MAX_TRADE_SIZE_USD: $500"
echo "  • STOP_LOSS_PCT: 2%"
echo "  • TAKE_PROFIT_PCT: 5%"
echo "  • LOOP_INTERVAL_SECONDS: 300 (5 min)"
echo ""

echo "📁 KEY FILES:"
echo "  • audit_final.py - Run full system verification"
echo "  • VIDEO_DEMO_READY.md - Detailed audit report"
echo "  • nexus_weights.json - Agent reputation scores"
echo "  • nexus_positions.json - Open positions"
echo "  • dashboard.html - Interactive UI"
echo ""

echo "🎬 VIDEO RECORDING TIPS:"
echo "  1. Start with clean terminal (clear cache if needed)"
echo "  2. Run audit first to verify all systems: python audit_final.py"
echo "  3. Start engine in one terminal, let it run for 1-2 cycles"
echo "  4. Show agent logs clearly (use --verbose flag)"
echo "  5. Click refresh button in dashboard to show real-time updates"
echo "  6. Highlight Risk Guardian veto in logs"
echo "  7. Point out consensus voting results"
echo "  8. Total demo: 3-5 minutes per cycle"
echo ""

echo "✅ PRE-DEMO CHECKLIST:"
echo "  ☐ Run audit_final.py - all systems green?"
echo "  ☐ Terminal 1 logs showing agent thinking?"
echo "  ☐ Dashboard loads at http://localhost:5000?"
echo "  ☐ Refresh button responds immediately?"
echo "  ☐ Auto-refresh interval selector works?"
echo "  ☐ Agent weights file readable?"
echo "  ☐ Network connection to PRISM/Kraken/RPC stable?"
echo "  ☐ Recording software ready?"
echo ""

echo "🎥 READY TO RECORD!"
echo ""
echo "Questions? Check:"
echo "  • VIDEO_DEMO_READY.md - Full audit report"
echo "  • main.py --help - Available options"
echo "  • config.py - All configuration parameters"
echo ""

exit 0
